import { ItemType, AccessoryCategory, InventoryItem } from "@/types/inventory";

const storeItems: Record<string, Record<string, InventoryItem>> = {
  clothing: {
    MUSICIAN_CLOTHES: {
      name: "MUSICIAN_CLOTHES",
      displayName: "Fancy Shirt",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Musician.svg",
      cost: 100,
      level: 0,
      description: "Fancy shirt",
    },
    DOCTOR_CLOTHES: {
      name: "DOCTOR_CLOTHES",
      displayName: "Scrubs",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Doctor.svg",
      cost: 100,
      level: 0,
      description: "Help save lives as a doctor or nurse!",
    },
    ASTRONAUT_CLOTHES: {
      name: "ASTRONAUT_CLOTHES",
      displayName: "Astronaut",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Astronaut.svg",
      cost: 100,
      level: 0,
      description: "Explore the planets and galaxies with this spacesuit!",
    },
    BUSINESS_CLOTHES: {
      name: "BUSINESS_CLOTHES",
      displayName: "Business",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Business.svg",
      cost: 100,
      level: 0,
      description: "Create economic growth through innovation!",
    },
    PAINTER_CLOTHES: {
      name: "PAINTER_CLOTHES",
      displayName: "Painter",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Painter.svg",
      cost: 100,
      level: 0,
      description: "Create beautiful art using your imagination!",
    },
    FUTURE_ITEM: {
      name: "FUTURE_ITEM",
      displayName: "Future Item",
      type: ItemType.CLOTHING,
      image: "",
      cost: 100,
      level: 2,
      description: "",
    },
    BLAH_BLAH: {
      name: "BLAH_BLAH",
      displayName: "Locked",
      type: ItemType.CLOTHING,
      image: "",
      cost: 100,
      level: 2,
      description: "",
    },
  },
  accessory: {
    MUSICIAN_SHOES: {
      name: "MUSICIAN_SHOES",
      displayName: "Musician Shoes",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.SHOES,
      image: "/store/shoes/Musician.svg",
      cost: 100,
      level: 0,
      description: "Musician...",
    },
    ASTRONAUT_SHOES: {
      name: "ASTRONAUT_SHOES",
      displayName: "Astronaut Shoes",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.SHOES,
      image: "/store/shoes/Astronaut.svg",
      cost: 100,
      level: 0,
      description: "Explore the planets and galaxies with this spacesuit!",
    },
    BUSINESS_SHOES: {
      name: "BUSINESS_SHOES",
      displayName: "Business Shoes",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.SHOES,
      image: "/store/shoes/Business.svg",
      cost: 100,
      level: 0,
      description: "Create economic growth through innovation!",
    },
    MUSICIAN_HAT: {
      name: "MUSICIAN_HAT",
      displayName: "Musician Hat",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.HAT,
      image: "/store/hats/Musician.svg",
      cost: 100,
      level: 0,
      description: "Musician...",
    },
    BUSINESS_HAT: {
      name: "BUSINESS_HAT",
      displayName: "Business Hat",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.HAT,
      image: "/store/hats/Business.svg",
      cost: 100,
      level: 0,
      description: "Create economic growth through innovation!",
    },
    DOCTOR_HAT: {
      name: "DOCTOR_HAT",
      displayName: "Doctor Hat",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.HAT,
      image: "/store/hats/Doctor.svg",
      cost: 100,
      level: 0,
      description: "Help save lives as a doctor or nurse!",
    },
    ASTRONAUT_HAT: {
      name: "ASTRONAUT_HAT",
      displayName: "Astronaut Hat",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.HAT,
      image: "/store/hats/Astronaut.svg",
      cost: 100,
      level: 0,
      description: "Something about astronauts!",
    },
    DOCTOR_ACCESSORY: {
      name: "DOCTOR_ACCESSORY",
      displayName: "First Aid",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.OCCUPATION,
      image: "/store/occupation/Doctor.svg",
      cost: 100,
      level: 0,
      description: "Help save lives as a doctor or nurse!",
    },
    BUSINESS_ACCESSORY: {
      name: "BUSINESS_ACCESSORY",
      displayName: "Briefcase",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.OCCUPATION,
      image: "/store/occupation/Business.svg",
      cost: 100,
      level: 0,
      description: "Create economic growth through innovation!",
    },
    MUSICIAN_ACCESSORY: {
      name: "MUSICIAN_ACCESSORY",
      displayName: "Saxophone",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.OCCUPATION,
      image: "/store/occupation/Musician.svg",
      cost: 100,
      level: 0,
      description: "Something about music!",
    },
    PALETTE_ACCESSORY: {
      name: "PALETTE_ACCESSORY",
      displayName: "Paint Palette",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.OCCUPATION,
      image: "/store/occupation/Palette.svg",
      cost: 100,
      level: 0,
      description: "Something about art!",
    },
    BRUSH_ACCESSORY: {
      name: "BRUSH_ACCESSORY",
      displayName: "Paint Brush",
      type: ItemType.ACCESSORY,
      category: AccessoryCategory.OCCUPATION,
      image: "/store/occupation/Brush.svg",
      cost: 100,
      level: 0,
      description: "Something about art!",
    },
  },
  background: {
    APPLE_TREE: {
      name: "APPLE_TREE",
      displayName: "Apple Tree",
      type: ItemType.BACKGROUND,
      image: "/store/backgrounds/Apple_Tree.svg",
      cost: 100,
      level: 0,
      description: "Enjoy a sunny day with yummy apples!",
    },
  },
  food: {
    PIZZA: {
      name: "PIZZA",
      displayName: "Pizza",
      type: ItemType.FOOD,
      image: "/store/foods/Pizza.svg",
      cost: 100,
      level: 0,
      description: "Pizza...",
    },
    AVOCADO: {
      name: "AVOCADO",
      displayName: "Avocado",
      type: ItemType.FOOD,
      image: "/store/foods/Avocado.svg",
      cost: 100,
      level: 0,
      description: "A fresh avocado...",
    },
    BREAD: {
      name: "BREAD",
      displayName: "Bread",
      type: ItemType.FOOD,
      image: "/store/foods/Bread.svg",
      cost: 100,
      level: 0,
      description: "A loaf of bread...",
    },
    BURGER: {
      name: "BURGER",
      displayName: "Burger",
      type: ItemType.FOOD,
      image: "/store/foods/Burger.svg",
      cost: 100,
      level: 0,
      description: "A delicious burger...",
    },
    CUPCAKE: {
      name: "CUPCAKE",
      displayName: "Cupcake",
      type: ItemType.FOOD,
      image: "/store/foods/Cupcake.svg",
      cost: 100,
      level: 0,
      description: "A sweet cupcake...",
    },
    EGG: {
      name: "EGG",
      displayName: "Egg",
      type: ItemType.FOOD,
      image: "/store/foods/Egg.svg",
      cost: 100,
      level: 2,
      description: "A single egg...",
    },
    FRIES: {
      name: "FRIES",
      displayName: "Fries",
      type: ItemType.FOOD,
      image: "/store/foods/Fries.svg",
      cost: 100,
      level: 2,
      description: "Crispy fries...",
    },
    LEMONADE: {
      name: "LEMONADE",
      displayName: "Lemonade",
      type: ItemType.FOOD,
      image: "/store/foods/Lemonade.svg",
      cost: 100,
      level: 2,
      description: "Refreshing lemonade...",
    },
  },
};

export default storeItems;
