import { ItemType, ItemPrice, InventoryItem } from "@/types/inventory";
import { getStreakItemCostForLevel } from "@/services/streak";

const storeItems: Record<string, Record<string, InventoryItem>> = {
  clothing: {
    MUSICIAN_CLOTHES: {
      name: "MUSICIAN_CLOTHES",
      displayName: "Fancy Shirt",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Musician.svg",
      cost: ItemPrice.CHEAP,
      level: 1,
      description: "Fancy shirt",
    },
    DOCTOR_CLOTHES: {
      name: "DOCTOR_CLOTHES",
      displayName: "Scrubs",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Doctor.svg",
      cost: ItemPrice.MEDIUM,
      level: 1,
      description: "Help save lives as a doctor or nurse!",
    },
    ASTRONAUT_CLOTHES: {
      name: "ASTRONAUT_CLOTHES",
      displayName: "Astronaut",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Astronaut.svg",
      cost: ItemPrice.EXPENSIVE,
      level: 1,
      description: "Explore the planets and galaxies with this spacesuit!",
    },
    RED_WINGS_CLOTHES: {
      name: "RED_WINGS_CLOTHES",
      displayName: "Red Wings",
      type: ItemType.CLOTHING,
      image: "/store/clothes/RedWings.png",
      cost: getStreakItemCostForLevel(1), // Dynamic: 60 coins for levels 1-4
      level: 1,
      description: "Fly high with these vibrant red wings! (Streak Required)",
      isStreakLocked: true,
      streakRequirement: 3, // Must have active streak (3+ days)
    },
    // Level 2 Items
    BUSINESS_CLOTHES: {
      name: "BUSINESS_CLOTHES",
      displayName: "Business",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Business.svg",
      cost: ItemPrice.CHEAP,
      level: 2,
      description: "Create economic growth through innovation!",
    },
    PAINTER_CLOTHES: {
      name: "PAINTER_CLOTHES",
      displayName: "Painter",
      type: ItemType.CLOTHING,
      image: "/store/clothes/Painter.svg",
      cost: ItemPrice.MEDIUM,
      level: 2,
      description: "Create beautiful art using your imagination!",
    },
    BLUE_WING_CLOTHES: {
      name: "BLUE_WING_CLOTHES",
      displayName: "Blue Wings",
      type: ItemType.CLOTHING,
      image: "/store/clothes/BlueWings.png",
      cost: ItemPrice.EXPENSIVE,
      level: 2,
      description: "Take flight with these cool blue wings!",
    },
    GREEN_WING_CLOTHES: {
      name: "GREEN_WING_CLOTHES",
      displayName: "Green Wings",
      type: ItemType.CLOTHING,
      image: "/store/clothes/GreenWings.png",
      cost: getStreakItemCostForLevel(2), // Dynamic: 60 coins for levels 1-4
      level: 2,
      description:
        "Soar through the sky with these green wings! (Streak Required)",
      isStreakLocked: true,
      streakRequirement: 3,
    },
    // Level 3 Items
    YELLOW_WINGS_CLOTHES: {
      name: "YELLOW_WINGS_CLOTHES",
      displayName: "Yellow Wings",
      type: ItemType.CLOTHING,
      image: "/store/clothes/YellowWings.png",
      cost: ItemPrice.CHEAP,
      level: 3,
      description: "Brighten up your look with sunny yellow wings!",
    },
    PINK_WING_CLOTHES: {
      name: "PINK_WING_CLOTHES",
      displayName: "Pink Wings",
      type: ItemType.CLOTHING,
      image: "/store/clothes/PinkWings.png",
      cost: ItemPrice.MEDIUM,
      level: 3,
      description: "Add a touch of elegance with these pink wings!",
    },
    FUTURE_ITEM: {
      name: "FUTURE_ITEM",
      displayName: "Future Item",
      type: ItemType.CLOTHING,
      image: "",
      cost: 100,
      level: 2,
      description: "",
    },
    BLAH_BLAH: {
      name: "BLAH_BLAH",
      displayName: "Locked",
      type: ItemType.CLOTHING,
      image: "",
      cost: 100,
      level: 2,
      description: "",
    },
  },
  shoes: {
    MUSICIAN_SHOES: {
      name: "MUSICIAN_SHOES",
      displayName: "Musician Shoes",
      type: ItemType.SHOES,
      image: "/store/shoes/Musician.svg",
      cost: ItemPrice.CHEAP,
      level: 1,
      description: "Musician...",
    },
    ASTRONAUT_SHOES: {
      name: "ASTRONAUT_SHOES",
      displayName: "Astronaut Shoes",
      type: ItemType.SHOES,
      image: "/store/shoes/Astronaut.svg",
      cost: ItemPrice.MEDIUM,
      level: 1,
      description: "Explore the planets and galaxies with this spacesuit!",
    },
    BUSINESS_SHOES: {
      name: "BUSINESS_SHOES",
      displayName: "Business Shoes",
      type: ItemType.SHOES,
      image: "/store/shoes/Business.svg",
      cost: ItemPrice.EXPENSIVE,
      level: 1,
      description: "Create economic growth through innovation!",
    },
  },
  hat: {
    MUSICIAN_HAT: {
      name: "MUSICIAN_HAT",
      displayName: "Musician Hat",
      type: ItemType.HAT,
      image: "/store/hats/Musician.svg",
      cost: ItemPrice.CHEAP,
      level: 1,
      description: "Musician...",
    },
    BUSINESS_HAT: {
      name: "BUSINESS_HAT",
      displayName: "Business Hat",
      type: ItemType.HAT,
      image: "/store/hats/Business.svg",
      cost: ItemPrice.MEDIUM,
      level: 1,
      description: "Create economic growth through innovation!",
    },
    DOCTOR_HAT: {
      name: "DOCTOR_HAT",
      displayName: "Doctor Hat",
      type: ItemType.HAT,
      image: "/store/hats/Doctor.svg",
      cost: ItemPrice.EXPENSIVE,
      level: 1,
      description: "Help save lives as a doctor or nurse!",
    },
    ASTRONAUT_HAT: {
      name: "ASTRONAUT_HAT",
      displayName: "Astronaut Hat",
      type: ItemType.HAT,
      image: "/store/hats/Astronaut.svg",
      cost: ItemPrice.CHEAP,
      level: 2,
      description: "Something about astronauts!",
    },
  },
  occupation: {
    DOCTOR_OCCUPATION: {
      name: "DOCTOR_OCCUPATION",
      displayName: "First Aid",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Doctor.svg",
      cost: ItemPrice.CHEAP,
      level: 1,
      description: "Help save lives as a doctor or nurse!",
    },
    BUSINESS_OCCUPATION: {
      name: "BUSINESS_OCCUPATION",
      displayName: "Briefcase",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Business.svg",
      cost: ItemPrice.MEDIUM,
      level: 1,
      description: "Create economic growth through innovation!",
    },
    MUSICIAN_OCCUPATION: {
      name: "MUSICIAN_OCCUPATION",
      displayName: "Saxophone",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Musician.svg",
      cost: ItemPrice.EXPENSIVE,
      level: 1,
      description: "Something about music!",
    },
    PALETTE_OCCUPATION: {
      name: "PALETTE_OCCUPATION",
      displayName: "Paint Palette",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Palette.svg",
      cost: ItemPrice.CHEAP,
      level: 2,
      description: "Something about art!",
    },
    BRUSH_OCCUPATION: {
      name: "BRUSH_OCCUPATION",
      displayName: "Paint Brush",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Brush.svg",
      cost: ItemPrice.MEDIUM,
      level: 2,
      description: "Something about art!",
    },
    SOCCER_OCCUPATION: {
      name: "SOCCER_OCCUPATION",
      displayName: "Soccer Ball",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Soccer.png",
      cost: ItemPrice.EXPENSIVE,
      level: 2,
      description: "Score goals and become a soccer champion!",
    },
    BASKETBALL_OCCUPATION: {
      name: "BASKETBALL_OCCUPATION",
      displayName: "Basketball",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Basketball.png",
      cost: ItemPrice.CHEAP,
      level: 3,
      description: "Shoot hoops and dominate the court!",
    },
    FOOTBALL_OCCUPATION: {
      name: "FOOTBALL_OCCUPATION",
      displayName: "Football",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Football.png",
      cost: ItemPrice.MEDIUM,
      level: 3,
      description: "Score touchdowns and win the championship!",
    },
    BASEBALL_OCCUPATION: {
      name: "BASEBALL_OCCUPATION",
      displayName: "Baseball",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Baseball.png",
      cost: ItemPrice.EXPENSIVE,
      level: 3,
      description: "Hit home runs and become a baseball legend!",
    },
    TENNIS_OCCUPATION: {
      name: "TENNIS_OCCUPATION",
      displayName: "Tennis Racket",
      type: ItemType.OCCUPATION,
      image: "/store/occupation/Tennis.png",
      cost: ItemPrice.CHEAP,
      level: 4,
      description: "Serve aces and win tennis tournaments!",
    },
  },
  background: {
    APPLE_TREE: {
      name: "APPLE_TREE",
      displayName: "Apple Tree",
      type: ItemType.BACKGROUND,
      image: "/store/backgrounds/Apple_Tree.png",
      cost: ItemPrice.CHEAP,
      level: 1,
      description: "Enjoy a sunny day with yummy apples!",
    },
  },
  food: {
    PIZZA: {
      name: "PIZZA",
      displayName: "Pizza",
      type: ItemType.FOOD,
      image: "/store/foods/Pizza.svg",
      cost: ItemPrice.CHEAP,
      level: 1,
      description: "Pizza...",
    },
    AVOCADO: {
      name: "AVOCADO",
      displayName: "Avocado",
      type: ItemType.FOOD,
      image: "/store/foods/Avocado.svg",
      cost: ItemPrice.MEDIUM,
      level: 1,
      description: "A fresh avocado...",
    },
    BREAD: {
      name: "BREAD",
      displayName: "Bread",
      type: ItemType.FOOD,
      image: "/store/foods/Bread.svg",
      cost: ItemPrice.EXPENSIVE,
      level: 1,
      description: "A loaf of bread...",
    },
    BURGER: {
      name: "BURGER",
      displayName: "Burger",
      type: ItemType.FOOD,
      image: "/store/foods/Burger.svg",
      cost: ItemPrice.CHEAP,
      level: 2,
      description: "A delicious burger...",
    },
    CUPCAKE: {
      name: "CUPCAKE",
      displayName: "Cupcake",
      type: ItemType.FOOD,
      image: "/store/foods/Cupcake.svg",
      cost: ItemPrice.MEDIUM,
      level: 2,
      description: "A sweet cupcake...",
    },
    EGG: {
      name: "EGG",
      displayName: "Egg",
      type: ItemType.FOOD,
      image: "/store/foods/Egg.svg",
      cost: ItemPrice.EXPENSIVE,
      level: 2,
      description: "A single egg...",
    },
    FRIES: {
      name: "FRIES",
      displayName: "Fries",
      type: ItemType.FOOD,
      image: "/store/foods/Fries.svg",
      cost: ItemPrice.CHEAP,
      level: 3,
      description: "Crispy fries...",
    },
    LEMONADE: {
      name: "LEMONADE",
      displayName: "Lemonade",
      type: ItemType.FOOD,
      image: "/store/foods/Lemonade.svg",
      cost: ItemPrice.MEDIUM,
      level: 3,
      description: "Refreshing lemonade...",
    },
  },
};

export default storeItems;
